/**
 * DSH plugin scaffold generator.
 *
 * Generates a complete, spec-compliant DSH plugin package from a few options,
 * following `docs/adding-a-package.zh.md`: package.json invariants
 * (`private`, `type: module`, `main: lib/index.js`, `types:
 * lib/types/index.d.ts`, `exports[.].types` first), a `src/index.ts` plugin
 * skeleton (`name` / `inject` / `apply(ctx, config)` / `Config`), a
 * tsconfig with `.ts`-suffix relative imports rewritten to `.js`, and a
 * README with the required sections.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export interface ScaffoldOptions {
  /** Plugin name (unscoped, kebab-case). */
  readonly name: string
  /** Package group (one of `core`/`llm`/`support`/`util`). */
  readonly group?: string
  /** Output directory (created when missing). */
  readonly outDir: string
  readonly description?: string
  /** Initial package version. Defaults to `0.1.0`. */
  readonly version?: string
  /** npm scope. Defaults to `@deepseek-ai`. */
  readonly namespace?: string
  /** Generate a dual-face package (declares `dsh.client` + `exports["./client"]`). */
  readonly dualFace?: boolean
  /** Generate a minimal vitest unit test for the plugin. */
  readonly withTests?: boolean
}

const PLUGIN_GROUPS = ['core', 'llm', 'support', 'util'] as const

/** Package id for a plugin (scope + name). */
export function packageId(options: Pick<ScaffoldOptions, 'namespace' | 'name'>): string {
  const ns = options.namespace ?? '@deepseek-ai'
  return `${ns}/${options.name}`
}

function validate(options: ScaffoldOptions): void {
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(options.name)) {
    throw new Error(`invalid plugin name: ${options.name} (use kebab-case, lowercase, digits and hyphens)`)
  }
  if (options.group && !(PLUGIN_GROUPS as readonly string[]).includes(options.group)) {
    throw new Error(`invalid group ${options.group}; expected one of ${PLUGIN_GROUPS.join(', ')}`)
  }
  if (!options.version && options.version !== undefined && !/^\d+\.\d+\.\d+$/.test(options.version)) {
    throw new Error(`invalid version: ${options.version}`)
  }
}

function pluginTsConfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2023"],
    "strict": true,
    "declaration": true,
    "declarationMap": false,
    "sourceMap": false,
    "outDir": "lib",
    "rootDir": "src",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "noUncheckedIndexedAccess": true,
    "allowImportingTsExtensions": true,
    "rewriteRelativeImportExtensions": true
  },
  "include": ["src/**/*.ts"]
}
`
}

function manifest(options: ScaffoldOptions): string {
  const id = packageId(options)
  const version = options.version ?? '0.1.0'
  const exportsObject = options.dualFace
    ? `  "exports": {
    ".": {
      "types": "./lib/types/index.d.ts",
      "default": "./lib/index.js"
    },
    "./client": {
      "types": "./lib/client/types/index.d.ts",
      "default": "./lib/client/index.js"
    }
  },`
    : `  "exports": {
    ".": {
      "types": "./lib/types/index.d.ts",
      "default": "./lib/index.js"
    }
  },`
  const dshField = options.dualFace
    ? `  "dsh": {
    "client": {
      "inject": "self-evolution"
    }
  },
`
    : ''
  return `{
  "name": "${id}",
  "version": "${version}",
  "private": true,
  "type": "module",
  "main": "lib/index.js",
  "types": "lib/types/index.d.ts",
${exportsObject}
${dshField}  "files": [
    "lib"
  ],
  "scripts": {
    "build": "tsc -b",
    "typecheck": "tsc -b --pretty false"
  },
  "peerDependencies": {
    "@deepseek-ai/cordis": "^4.0.1"
  },
  "devDependencies": {
    "@deepseek-ai/cordis": "^4.0.1",
    "typescript": "^5.5.4"
  }
}
`
}

function pluginIndex(options: ScaffoldOptions, description: string): string {
  return `/**
 * ${options.name} — ${description}
 *
 * Generated by the self-evolution toolkit scaffold generator
 * (docs/adding-a-package.zh.md conventions).
 */
import type { Context } from '@deepseek-ai/cordis'
import Schema from '@deepseek-ai/schemastery'

export const name = '${options.name}'
export const inject: (keyof Context & string)[] = []

export interface Config {
  /** Set of flags this plugin reads at apply time. */
  readonly ${options.name.replace(/-/g, '_')}_enabled: boolean
}

export const Config = Schema.object({
  ${options.name.replace(/-/g, '_')}_enabled: Schema.boolean().default(true),
})

export function apply(ctx: Context, config: Config) {
  if (!config.${options.name.replace(/-/g, '_')}_enabled) return

  // Register only reversible side effects; every registration is torn down
  // on plugin reload.
  ctx.effect(() => {
    ctx.logger('${options.name}').info('plugin mounted')
    return () => {
      ctx.logger('${options.name}').info('plugin unmounted')
    }
  })
}
`
}

function pluginReadme(options: ScaffoldOptions, description: string): string {
  const id = packageId(options)
  const clientSection = options.dualFace
    ? `## Client

This package is dual-face: it ships a browser half at \`exports["./client"]\`
(declared via \`dsh.client\`), so the Web UI can render a plugin panel
(docs/cookbook/extension-cookbook.zh.md).
`
    : ''
  return `# ${id}

${description}

## Usage

Mount the plugin in the DSH harness configuration:

\`\`\`yaml
plugins:
  ${id}: {}
\`\`\`

## Configuration

See \`src/index.ts\` — \`Config\` is validated by schemastery on mount.

## Interfaces & Events

- Consumes: \`ctx.logger\` (cordis)
- Contributes: none yet

## License

See the DSH project license.
${clientSection}
## Development

\`\`\`sh
pnpm install
pnpm run typecheck
pnpm run build
\`\`\`
`
}

function pluginTest(options: ScaffoldOptions): string {
  return `import { describe, expect, it } from 'vitest'
import { name } from '../src/index.ts'

describe('${options.name}', () => {
  it('exports a plugin name in kebab-case', () => {
    expect(name).toBe('${options.name}')
  })
})
`
}

/** Generate a complete plugin package; returns the created file paths. */
export function scaffoldPlugin(options: ScaffoldOptions): readonly string[] {
  validate(options)
  if (existsSync(join(options.outDir, 'package.json'))) {
    throw new Error(`refusing to scaffold into non-empty directory: ${options.outDir}`)
  }
  const description = options.description ?? 'A DSH plugin generated by the self-evolution toolkit.'

  const files: Record<string, string> = {
    'package.json': manifest(options),
    'tsconfig.json': pluginTsConfig(),
    'src/index.ts': pluginIndex(options, description),
    'README.md': pluginReadme(options, description),
    '.npmrc': 'auto-install-peers=false\n',
  }
  if (options.withTests) {
    files['tests/index.spec.ts'] = pluginTest(options)
  }
  if (options.dualFace) {
    files['src/client/index.ts'] = `/**
 * Browser half of ${options.name}.
 * Rendered by the DSH Web UI via \`ctx.slots.register\`.
 */
export const title = '${options.name}'
export default function Panel() {
  return { name: '${options.name}-panel' }
}
`
  }

  const created: string[] = []
  for (const [rel, content] of Object.entries(files)) {
    const target = join(options.outDir, rel)
    mkdirSync(target.split(/[\\/]/).slice(0, -1).join('/') || '.', { recursive: true })
    writeFileSync(target, content, 'utf8')
    created.push(target)
  }
  return created
}
